# Generated by Django 6.1 on 2026-08-12 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255, verbose_name='Product ID')),
                ('title', models.CharField(max_length=500, verbose_name='Product Title')),
                ('provider', models.CharField(max_length=100, verbose_name='Provider Store')),
                ('current_price', models.PositiveBigIntegerField(default=0, verbose_name='Current Price Toman')),
                ('target_price', models.PositiveBigIntegerField(verbose_name='Target Price Toman')),
                ('product_url', models.URLField(max_length=1000, verbose_name='Product URL')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Image URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active Alert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Product Watchlist',
                'verbose_name_plural': 'Product Watchlists',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product_id', 'provider')},
            },
        ),
    ]
