# Generated by Django 6.1 on 2026-08-09 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokentransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Token Transaction', 'verbose_name_plural': 'Token Transactions'},
        ),
        migrations.AlterModelOptions(
            name='tokenwallet',
            options={'verbose_name': 'Token Wallet', 'verbose_name_plural': 'Token Wallets'},
        ),
        migrations.AlterField(
            model_name='tokentransaction',
            name='amount',
            field=models.IntegerField(verbose_name='Amount Change'),
        ),
        migrations.AlterField(
            model_name='tokentransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tokentransaction',
            name='transaction_type',
            field=models.CharField(choices=[('SIGNUP_BONUS', 'Signup Bonus'), ('SEARCH_CONSUMPTION', 'Search Consumption'), ('MANUAL_RECHARGE', 'Manual Recharge')], max_length=30, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='tokentransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='tokenwallet',
            name='balance',
            field=models.PositiveIntegerField(default=50, verbose_name='Token Balance'),
        ),
        migrations.AlterField(
            model_name='tokenwallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
