# Generated by Django 6.1 on 2026-08-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_alter_tokentransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenwallet',
            name='balance',
            field=models.PositiveIntegerField(default=10, verbose_name='Token Balance'),
        ),
    ]
